typography_spectrum: 0
color:
  brandColors:
    - '#070707'
    - '#fefefe'
    - '#444444'
    - '#898989'
    - '#d7d7d7'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: instagram.com/sojustbecause
  email: sojustbecause@gmail.com
  name: Ercan
name: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sojustbecause
purpose: []
