typography_spectrum: 0.2892500211019069
color:
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
  brandStrength: 0.10260486439801753
  lightness: 0.9593357394915074
  saturation: 0.8441650569438934
  rhythmicContrast: 0.5045492292847484
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.015765431337058544
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: 'http://www.instagram.com/sojustbecause'
  email: sojustbecause@gmail.com
  name: Ercan Küçükaslan
name: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sojustbecause
purpose: []
