typography_spectrum: 0.60806
color:
  brandColors:
    - '#111111'
    - '#4f4f4f'
    - '#fcfcfc'
    - '#838383'
    - '#dbdbdb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23289
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: 'http://www.instagram.com/sojustbecause'
  email: sojustbecause@gmail.com
  name: Ercan Küçükaslan
name: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sojustbecause
purpose: []
