name: sojustbecause
favicon: null
layout_spectrum: 0.65804
typography_spectrum: 0.60806
author:
  url: instagram.com/sojustbecause
  email: sojustbecause@gmail.com
  name: Ercan
title: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#7d7f72'
    - '#bcbfa4'
    - '#3f575b'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
