name: sojustbecause
favicon: null
layout_spectrum: 0.23976086475886405
typography_spectrum: 0.7094456038903445
author:
  url: 'http://www.instagram.com/sojustbecause'
  email: sojustbecause@gmail.com
  name: Ercan Küçükaslan
title: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.30770994117483497
  lightness: 0.18377330200746655
  saturation: 0.30625483742915094
  rhythmicContrast: 0.6280083912424743
purpose: []
