name: sojustbecause
favicon: null
layout_spectrum: 0.9738720622844994
typography_spectrum: 0.8127873616758734
author:
  url: 'http://www.instagram.com/sojustbecause'
  email: sojustbecause@gmail.com
  name: Ercan Küçükaslan
title: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1a0f'
    - '#576781'
    - '#faf7f2'
    - '#8290aa'
    - '#b5b7c3'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
