name: sojustbecause
favicon: null
layout_spectrum: 0.65804
typography_spectrum: 0.60806
author:
  url: instagram.com/sojustbecause
  email: sojustbecause@gmail.com
  name: Ercan
title: sojustbecause
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#4f4f4f'
    - '#fcfcfc'
    - '#838383'
    - '#dbdbdb'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
